### ISSUE TITLE
Add logo usage guidelines

### ISSUE THREAD

**Issue by berendt** [osism/logos#1]

**Comment by tibeer** [comment]
maybe also add a license...

**Comment by berendt** [comment]
Not sure if a license is required. It's our logo and our word mark.

For the trademark policy: https://openinfra.dev/legal/trademark-policy
For the usage guideline: I think something like https://www.openstack.org/brand/openstack-logo/.

**Comment by aeroflydesign** [comment]
Generally speaking, no one is allowed to use someone else's logo so easily. So if we want to make our logo available, it makes sense to set up a kind of press area, where the logo and the instructions about the context in which the logo may be placed, can be downloaded in a zip package.

**Comment by berendt** [comment]
@aeroflydesign Makes sense to me. Please take this with you for the new website.

**Comment by aeroflydesign** [comment]
I have made an entry in my task "#Homepage Fragenkatalog" under 3.1

**Comment by aeroflydesign** [comment]
I have made an entry in my task.

**Comment by tibeer** [comment]
Following the conversation, I consider this as resolved.
